name: Issue Assignment Linting

on:
  issues:
    types: [assigned]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  move-assigned-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Move assigned issues to "In progress" column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/sunshower-io/zephyr/projects/1
          GITHUB_PROJECT_COLUMN_NAME: In progress